version: "3.5"
services:
  nginx:
    image: nginx:1.17.3-alpine
    container_name: nginx
    restart: always
    # depends_on:
    #   - flask
    ports:
      - "5000:5000"
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - outside
networks:
  outside:
    external:
      name: flaskPostgres
