version: "3.5"
services:
  flask:
    image: flask
    restart: always
    container_name: flask
    ports:
      - 5000:5000
    networks:
      - outside
networks:
  outside:
    external:
      name: flaskPostgres
