version: "3.5"
services:
  flask:
    image: flask
    restart: always
    container_name: flask
    expose:
      - 5000
    networks:
      - outside

networks:
  outside:
    external:
      name: flaskPostgres
