version: "3.5"
services:
  postgres:
    image: postgres:9.5
    restart: always
    container_name: postgres
    # env_file: database.conf
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=flask
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      # - 6551:5432
    networks:
      - outside
networks:
  outside:
    external:
      name: flaskPostgres
